//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/de_aztec.html
models/skeleton.mdl
sprites/ikgrass1.spr
sprites/ikgrass2.spr
sprites/ikgrass3.spr
sound/ambience/rain.wav
models/pred_plant.mdl
sprites/glow02.spr
sound/ambience/thunder_clap.wav
gfx/env/doom1bk.tga
gfx/env/doom1dn.tga
gfx/env/doom1ft.tga
gfx/env/doom1lf.tga
gfx/env/doom1rt.tga
gfx/env/doom1up.tga
overviews/de_aztec.txt
overviews/de_aztec.bmp
models/abone_template1.mdl
maps/de_aztec.bsp
maps/de_aztec.txt
